### ISSUE TITLE
Main State Machine

### ISSUE THREAD

**Issue by MrFlynn** [MrFlynn/micro-mega#3]
This issue goes over some ideas on how to implement the main state machine.

## Boot Process
This basically involves reading all file information out of storage into two arrays: one that holds the filename and one that holds the starting and ending addresses of the file contents.
- Read metadata starting index and data starting index into memory.
- Queue up 8 reads for the filename. `returnfunc` should insert each character into a string and then on the last read, append to the filename array. 
- Queue up 2 reads for starting and ending addresses and append them to 2d array for the respective file.
... And repeat the last two steps for all files.

### Variables:
- Some sort of index for the file being worked on. This is reset every 10 reads.
- File index. Increments every 10 reads. Between 0 and 16.
- Filename character buffer. Used to store characters as they are being read in.

### Functions:
- Function to each set the value of the starting addresses for file information and where new file data can be written.
- Function to append characters to buffer between counts 0 and 7. Should ignore null-terminator and `0xFF`.
- Function to add to starting and ending addresses. Increments file index when first index `>=` 10.

_Note_: both functions should increment first index. 

### Other Information:
Utilize standard storage operations where possible.

## Todo List:
- [x] Sketch out and refine state machine.
- [x] Add the variables listed above.
- [x] Implement the above functions.
- [x] Implement boot process for state machine.
