### ISSUE TITLE
Fix Compiler Warnings

### ISSUE THREAD

**Issue by MrFlynn** [MrFlynn/micro-mega#4]
There seems to be a lot of conversion errors (especially around pointers) with the current code, so some cleanup will be required in order to get it functional.

### Todos:
- [x] Visit each compiler warning and determine the issue.
- [x] Try to repair easy problems with warnings (i.e. simple errors like incompatible type where a pointer isn't being passed when it should).
- [x] Rethink message queue variable for storing characters. Might want to convert them to `uint8_t` when placing them into the queue.

**Comment by MrFlynn** [comment]
Files changed during this process:
- write_sm.c
- queue.h
- storage.c
- common.h
